Wizard_Aydin_Olga/Models/WizardModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wizard_Aydin_Olga.Models;

namespace Wizard_Aydin_Olga.Models
{
    public class WizardModel : Controller
    {
        public int SpielerAnzahl { get; set; }
        public int Runde { get; set; }
        public string Trumpf { get; set; }
        public List<Karte> KartenDeck { get; set; }
        public List<Spieler> SpielerListe { get; set; }

        public class Karte
        {
            public string KartenFarbe { get; set; }
            public int KartenWert { get; set; }
            public bool IstWizard { get; set; }
            public bool IstNarr { get; set; }
            public string BildPfad { get; set; }
        }
        public class Spieler
        {
            public int PunkteProRunde { get; set; }
            public string SpielerName { get; set; }
            public List<Karte> KartenListe { get; set; }
            public int GemachteStiche { get; set; }
            public int AngesagteStiche { get; set; }
        }
    }
}

Wizard_Aydin_Olga/Controllers/WizardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wizard_Aydin_Olga.Models;
using Wizard_Aydin_Olga.Controllers;
using System.Threading.Tasks;

namespace Wizard_Aydin_Olga.Controllers
{
    public class WizardController : Controller
    {
        public static WizardModel wizardModel;

        public ActionResult StartView()
        {
            return View();
        }


        [HttpPost]
        public ActionResult StartView(WizardModel model)
        {
            model.Runde = 1;
            model.SpielerAnzahl = 2;

            Random rand = new Random();

            model.Trumpf = TrumpfBestimmen();

            DeckMischen(model);

            for (int i = 0; i < model.SpielerAnzahl; i++)
            {
                if (model.SpielerListe[i].SpielerName == null)
                {
                    int spielerZahl = i + 1;

                    model.SpielerListe[i].SpielerName = "Spieler " + spielerZahl;
                }

                model.SpielerListe[1].AngesagteStiche = KIGegnerStiche(model);

                List<WizardModel.Karte> kartenAufDerHand = new List<WizardModel.Karte>();

                for (int r = 0; r < model.Runde; r++)
                {
                    kartenAufDerHand.Add(model.KartenDeck.FirstOrDefault());

                    model.SpielerListe[i].KartenListe = kartenAufDerHand;

                    model.KartenDeck.RemoveAt(0);
                }
            }

            wizardModel = model;

            return View("GameView", wizardModel);
        }

        private int KIGegnerStiche(WizardModel model)
        {
            int randomStiche;

            Random random = new Random();

            int maxStiche = model.Runde + 1;

            randomStiche = random.Next(0, maxStiche);

            return randomStiche;
        }

        [HttpPost]
        public ActionResult GameView(WizardModel model)
        {
            for (int i = 0; i < 2; i++)
            {
                wizardModel.SpielerListe[i].AngesagteStiche = model.SpielerListe[i].AngesagteStiche;
                wizardModel.SpielerListe[i].GemachteStiche = model.SpielerListe[i].GemachteStiche;
            }
            model = wizardModel;

            DeckMischen(model);

            Random rand = new Random();

            model.Runde++;

            for (int i = 0; i < model.SpielerAnzahl; i++)
            {
                model.SpielerListe[i].PunkteProRunde = SticheAuswerten(model.SpielerListe[i]);

                model.SpielerListe[1].AngesagteStiche = KIGegnerStiche(model);

                List<WizardModel.Karte> kartenAufDerHand = new List<WizardModel.Karte>();

                for (int r = 0; r < model.Runde; r++)
                {
                    kartenAufDerHand.Add(model.KartenDeck.FirstOrDefault());

                    model.SpielerListe[i].KartenListe = kartenAufDerHand;

                    model.KartenDeck.RemoveAt(0);
                }
                wizardModel = model;
            }
            return View(wizardModel);
        }

        public void DeckMischen(WizardModel model)
        {
            Random rand = new Random();

            List<WizardModel.Karte> kartenImDeck = new List<WizardModel.Karte>();

            if (model.KartenDeck == null)
            {
                kartenImDeck.Add(RandomKarte(model, rand));
                model.KartenDeck = kartenImDeck;
            }

            int s = 60;

            foreach (WizardModel.Spieler spieler in model.SpielerListe)
            {
                if (spieler.KartenListe != null)
                {
                    s = 60 - spieler.KartenListe.Count();
                }
            }

            for (int i = 0; model.KartenDeck.Count() < s; i++)
            {
                WizardModel.Karte karte = new WizardModel.Karte();

                karte = RandomKarte(model, rand);

                if (kartenImDeck.Any(x => x.KartenFarbe == karte.KartenFarbe && x.KartenWert == karte.KartenWert))
                {
                    kartenImDeck.Remove(karte);
                }
                else
                {
                    kartenImDeck.Add(karte);
                }
                model.KartenDeck = kartenImDeck;
            }
            wizardModel = model;
        }

        public WizardModel.Karte RandomKarte(WizardModel model, Random rand)
        {
            int number;

            WizardModel.Karte karte = new WizardModel.Karte();

            number = rand.Next(1, 16);

            karte.KartenWert = number;

            string[] farben = { "rote", "blaue", "gruene", "gelbe" };

            int index = rand.Next(farben.Length);

            karte.KartenFarbe = farben[index];

            if (number == 14)
            {
                karte.IstNarr = true;
                karte.BildPfad = "narr1.png";
            }
            else if (number == 15)
            {
                karte.IstWizard = true;
                karte.BildPfad = "zauberer1.png";
            }
            else
            {
                karte.BildPfad = karte.KartenFarbe + karte.KartenWert.ToString() + ".png";
            }

            return karte;
        }

        public string TrumpfBestimmen()
        {
            string[] farben = { "rot", "blau", "gruen", "gelb" };
            Random rand = new Random();

            int index = rand.Next(farben.Length);

            string trumpf = farben[index];

            return trumpf;
        }

        public int SticheAuswerten(WizardModel.Spieler spieler)
        {
            if (spieler.GemachteStiche == spieler.AngesagteStiche)
            {
                for (int s = 1; s <= spieler.GemachteStiche; s++)
                {
                    spieler.PunkteProRunde += 10;
                }
                spieler.PunkteProRunde += 20;
            }
            else if (spieler.GemachteStiche != spieler.AngesagteStiche)
            {
                if (spieler.GemachteStiche > spieler.AngesagteStiche)
                {
                    int differenz;
                    differenz = spieler.GemachteStiche - spieler.AngesagteStiche;

                    for (int f = 1; f <= differenz; f++)
                    {
                        spieler.PunkteProRunde -= 10;
                    }
                }
                else if (spieler.GemachteStiche < spieler.AngesagteStiche)
                {
                    int unterschied;
                    unterschied = spieler.AngesagteStiche - spieler.GemachteStiche;

                    for (int s = 1; s <= unterschied; s++)
                    {
                        spieler.PunkteProRunde -= 10;
                    }

                }
            }
            return spieler.PunkteProRunde;
        }
    }
}

Wizard_Aydin_Olga/Views/Shared/_Layout.cshtml
@model Wizard_Aydin_Olga.Models.WizardModel
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Wizard Online</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <link rel="stylesheet" href="../../Content/gameView.css">
    <script type="text/javascript" src="../../Scripts/base.js"></script>
    <script type="text/javascript" src="../../Scripts/dragndrop.js"></script>
</body>
</html>

Wizard_Aydin_Olga/Views/Wizard/GameView.cshtml
@model Wizard_Aydin_Olga.Models.WizardModel
@using (Html.BeginForm("GameView", "Wizard", FormMethod.Post))
{
    <div class="lightboxTricksOuter">
        <div class="lightboxTricksInner">
            <p>Wie viele Stiche <br /> machst du?</p>
            <div class="trickamountContainer">
                @for (int i = 0; i <= Model.Runde; i++)
                {
                    <div class="trick">
                        <input id=@i type="radio" name="tricks" value=@i />
                        <label for=@i>@i</label>
                    </div>
                }
            </div>
            <div class="confirmationTricks">Bestätigen</div>
        </div>
    </div>
    @*<div class="lightboxEvaluation">
        <div class="evaluationText">
            <p></p>
        </div>
    </div>*@
    <div class="playingGround" data-round="@Model.Runde">
        <div class="opponentsCardDeck noTurn">
            <div class="startEvaluation">
                <input id="startEvaluation" class="children" value="Auswertung starten" />
            </div>
            <div class="startEvaluationFinal">
                <input id="startEvaluationFinal" type="submit" class="noChildren" value="Auswertung starten" />
                @Html.TextBoxFor(s => s.SpielerListe[0].GemachteStiche, new { id = "ownTricks", style = "visibility: hidden; height: 0px; width: 0px" })
                @Html.TextBoxFor(r => r.SpielerListe[0].AngesagteStiche, new { id = "ownTricksGuess", style = "visibility: hidden; height: 0px; width: 0px" })
                @Html.TextBoxFor(s => s.SpielerListe[1].GemachteStiche, new { id = "botTricks", style = "visibility: hidden; height: 0px; width: 0px" })
                @Html.TextBoxFor(r => r.SpielerListe[1].AngesagteStiche, new { id = "botTricksGuess", style = "visibility: hidden; height: 0px; width: 0px" })
            </div>
            <div class="opponentCardWrapper">
                @foreach (var karte in Model.SpielerListe[1].KartenListe)
                {
                    <div class="card" data-color="@karte.KartenFarbe" data-value="@karte.KartenWert" draggable="true" ondragstart="onDragStart(event);">
                        <img class="middle" src="../Content/Karten/@karte.BildPfad" />
                        <img class="initial" src="../Content/Karten/behind.png" />
                    </div>
                }
            </div>
        </div>
        <div id="playingBoard" class="playingBoard" ondragover="onDragOver(event);" ondrop="onDrop(event);"></div>
        <div class="ownCardDeck turn">
            <div class="turnOver">Zug beenden</div>
            <div class="ownCardWrapper">
                @foreach (var karte in Model.SpielerListe[0].KartenListe)
                {
                    <div class="card" data-color="@karte.KartenFarbe" data-value="@karte.KartenWert" draggable="true" ondragstart="onDragStart(event);">
                        <img src="../Content/Karten/@karte.BildPfad" />
                    </div>
                }
            </div>
        </div>

        <div id="opponentTrickAmount"><p><span class="placeholder">0</span> gemachte Stiche</p></div>
        <div id="ownTrickAmount"><p><span class="placeholder">0</span> gemachte Stiche</p></div>

        <div class="trumpDisplay">
            <p>Trumpf:</p>
            <div class="@Model.Trumpf"></div>
        </div>
        <div class="pointBoard">
            <div class="firstRow row">
                <div class="round">&nbsp;</div>
                <div class="playerOnePoints"><p class="playerOneName">@Model.SpielerListe[0].SpielerName</p></div>
                <div class="playerTwoPoints"><p class="playerTwoName">@Model.SpielerListe[1].SpielerName</p></div>
            </div>
                <div class="row" data-round="@Model.Runde">
                    <div class="round"><p>@Model.Runde</p></div>
                    <div class="playerOnePoints"><p>@Model.SpielerListe[0].PunkteProRunde</p></div>
                    <div class="playerOneTricks"><p>@Model.SpielerListe[0].AngesagteStiche</p></div>
                    <div class="playerTwoPoints"><p>@Model.SpielerListe[1].PunkteProRunde</p></div>
                    <div class="playerTwoTricks"><p>@Model.SpielerListe[1].AngesagteStiche</p></div>
                </div>
        </div>
    </div>

}

Wizard_Aydin_Olga/Views/Wizard/StartView.cshtml
@model Wizard_Aydin_Olga.Models.WizardModel
﻿

<div class="startText">
    <h1>Willkommen, anstrebender Zauberer!</h1>
    <p>Möchtest Du Deine Sinne erweitern?</p>
    <p>Möchtest Du die Herausforderung bestreiten,<br /> Deine Gabe der Vorhersehung zu entwickeln und zu festigen?</p>
    <p>Dann gib Deinen Namen und den Deines Gegners ein und drück auf den Knopf!</p>

    @using (Html.BeginForm("StartView", "Wizard", FormMethod.Post))
    {
        <div class="nameBox">
            <div class="firstPlayerInput">
                <label for="SpielerName1">Erster Spieler</label>
                @Html.TextBoxFor(model => model.SpielerListe[0].SpielerName)
            </div>
            <div class="secondPlayerInput">
                <label for="SpielerName2">Zweiter Spieler</label>
                @Html.TextBoxFor(model => model.SpielerListe[1].SpielerName)
            </div>
            <button type="submit">Spiel starten</button>
        </div>
    }
</div>